language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t RazieL/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true RazieL/docker-react npm run test  